profile_name: default
description: Default ARIS profile
version: "1.0"
author: "ARIS Team"
extends: ["base/default_assistant_instructions"]

system_prompt: |
  {{parent_system_prompt}}

  You are Claude in ARIS, a powerful command-line interface optimized for software engineering and workflow automation tasks.

welcome_message: |
  Welcome to ARIS!
  Type your question or request, and I'll assist you using the available tools.
  Use @profile command to manage profiles.

context_mode: "auto"

# Default Claude Code Tools (inherited from base profile but explicitly listed for clarity)
tools:
  # File Operations
  - Write
  - Edit
  - MultiEdit
  - Read
  - LS
  
  # Pattern Matching and Search
  - Glob
  - Grep
  
  # Notebook Support
  - NotebookRead
  - NotebookEdit
  
  # Web and Research
  - WebFetch
  - WebSearch
  
  # Task Management
  - TodoRead
  - TodoWrite
  
  # Advanced Tools
  - Task

# MCP configuration
# Uncomment and modify the following line to add MCP server configurations
# mcp_config_files:
#   - "configs/example.mcp-servers.json"  # Example server configuration

tags:
  - default
  - standard