profile_name: default
description: Default ARIS profile
version: "1.0"
author: "ARIS Team"
extends: ["base/default_assistant_instructions"]

system_prompt: |
  {{parent_system_prompt}}

  You are Claude in ARIS, a powerful command-line interface optimized for software engineering and workflow automation tasks.

welcome_message: |
  Welcome to ARIS!
  Type your question or request, and I'll assist you using the available tools.
  Use @profile command to manage profiles.

context_mode: "auto"

# Default Claude Code Tools (inherited from base profile but explicitly listed for clarity)
tools:
  # File Operations
  - Write
  - Edit
  - MultiEdit
  - Read
  - LS
  
  # Pattern Matching and Search
  - Glob
  - Grep
  
  # Notebook Support
  - NotebookRead
  - NotebookEdit
  
  # Web and Research
  - WebFetch
  - WebSearch
  
  # Task Management
  - TodoRead
  - TodoWrite
  
  # Advanced Tools
  - Task

  # Safe Bash Commands (Common file operations and system commands)
  - "Bash(ls:*)"           # List directory contents
  - "Bash(cp:*)"           # Copy files and directories
  - "Bash(mv:*)"           # Move/rename files and directories
  - "Bash(mkdir:*)"        # Create directories
  - "Bash(rmdir:*)"        # Remove empty directories
  - "Bash(cat:*)"          # Display file contents
  - "Bash(head:*)"         # Show first lines of files
  - "Bash(tail:*)"         # Show last lines of files
  - "Bash(wc:*)"           # Count lines, words, characters
  - "Bash(grep:*)"         # Search text patterns
  - "Bash(find:*)"         # Find files and directories
  - "Bash(pwd:*)"          # Print working directory
  - "Bash(date:*)"         # Display current date/time
  - "Bash(whoami:*)"       # Display current user
  - "Bash(echo:*)"         # Display text
  - "Bash(touch:*)"        # Create empty files or update timestamps

# MCP configuration
# Uncomment and modify the following line to add MCP server configurations
# mcp_config_files:
#   - "configs/example.mcp-servers.json"  # Example server configuration

tags:
  - default
  - standard